<!doctype html>
<html>
	<head>
		<meta charset="utf-8"/>

<link rel="stylesheet" type="text/css" href="main.css">
<link rel="SHORTCUT ICON" href="favicon.ico"> 
<title>DV <? echo "..".substr($f,-10)."/".$dat."|".$q."|".$HTTP_HOST; ?> </title>

<script type="text/javascript" language="javascript">
  function open_window(Seite)
  {
   NeuesFenster = window.open(Seite, "Anzeigebeipiel", "width=500,height=500,scrollbars,screenX=50,screenY=50");
   NeuesFenster.focus();
  }

</script>

</head>
<?php

echo "<body>";

echo "<a href=\"$URL_to_Mainpage\">zur&uuml;ck</a> zur Hauptseite<br><br>\n";

?>
